#!/bin/bash
bin/rspec spec/features/smokes_spec.rb --tag smoke &
bin/rspec spec/features/smokes_spec.rb --tag smoke &
bin/rspec spec/features/smokes_spec.rb --tag smoke &
bin/rspec spec/features/smokes_spec.rb --tag smoke &
bin/rspec spec/features/smokes_spec.rb --tag smoke &
bin/rspec spec/features/smokes_spec.rb --tag smoke &
bin/rspec spec/features/smokes_spec.rb --tag smoke &
bin/rspec spec/features/smokes_spec.rb --tag smoke &
bin/rspec spec/features/smokes_spec.rb --tag smoke &
bin/rspec spec/features/smokes_spec.rb --tag smoke &
bin/rspec spec/features/smokes_spec.rb --tag smoke &
bin/rspec spec/features/smokes_spec.rb --tag smoke &
bin/rspec spec/features/smokes_spec.rb --tag smoke &
bin/rspec spec/features/smokes_spec.rb --tag smoke &
bin/rspec spec/features/smokes_spec.rb --tag smoke &
bin/rspec spec/features/smokes_spec.rb --tag smoke &
bin/rspec spec/features/smokes_spec.rb --tag smoke &
bin/rspec spec/features/smokes_spec.rb --tag smoke &
bin/rspec spec/features/smokes_spec.rb --tag smoke &
bin/rspec spec/features/smokes_spec.rb --tag smoke &